name: tdlib
description: Dart port of the Telegram Database Library (TDLib)
version: 0.1.0
author:  Aidan T. Manning <periodicaidan@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  ffi: '^0.1.1'
  path: '^1.6.4'

dev_dependencies:
  pedantic: '^1.7.0'
  test: '^1.6.0'
